import { useEffect, useState } from 'react';
import { adminAffiliates, adminAuditLogs, adminReferrals } from '@/lib/api';

export function AdminDashboard({ onBack }: { onBack: () => void }) {
  const [tab, setTab] = useState('Overview'); const [data, setData] = useState<any[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(''); try { const fn = tab==='Affiliates'?adminAffiliates:tab==='Referrals'?adminReferrals:tab==='Audit Log'?adminAuditLogs:adminAffiliates; setData(await fn()); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load admin data.'); } finally { setLoading(false); } };
  useEffect(()=>{void load()},[tab]);
  return <main className="app-shell min-h-screen px-4 pt-safe"><button className="icon-button" onClick={onBack}>Back</button><h1 className="section-title mt-5">Admin Dashboard</h1><nav className="mt-4 grid grid-cols-2 gap-2">{['Overview','Affiliates','Referrals','Administrators','Audit Log'].map(x=><button key={x} className="icon-button" onClick={()=>setTab(x)}>{x}</button>)}</nav>{loading?<div className="glass-card mt-5 h-48 animate-pulse" aria-label="Loading admin data"/>:error?<div className="mt-5"><p role="alert">{error}</p><button className="primary-button mt-3" onClick={load}>Retry</button></div>:tab==='Overview'?<div className="mt-5 grid grid-cols-2 gap-3">{[['Total affiliates',data.length],['Active affiliates',data.filter(x=>x.account_status==='ACTIVE').length],['Revoked affiliates',data.filter(x=>x.account_status==='REVOKED').length]].map(([k,v])=><div className="glass-card p-4" key={String(k)}><p className="text-sm text-zinc-400">{k}</p><p className="mt-2 text-2xl">{v}</p></div>)}</div>:<section className="mt-5 space-y-3">{data.length===0?<p className="text-zinc-400">No {tab.toLowerCase()} found.</p>:data.map((x:any)=><div className="glass-card p-4" key={x.id}><b>{x.username ? `@${x.username}` : x.first_name || `#${x.id}`}</b><p className="text-sm text-zinc-400">{x.account_status || x.action || x.status || ''}</p></div>)}</section>}</main>;
}
