import { useEffect, useState } from 'react';
import { adminAdministrators, adminAffiliates, adminAuditLogs, adminPayout, adminReferral, adminReferrals, adminRestore, adminRevoke } from '@/lib/api';

export function AdminDashboard({onBack}:{onBack:()=>void}) {
 const [tab,setTab]=useState('Overview'); const [items,setItems]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null); const [detail,setDetail]=useState<any>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [pending,setPending]=useState(false); const [notice,setNotice]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const fn=tab==='Affiliates'?adminAffiliates:tab==='Referrals'?adminReferrals:tab==='Administrators'?adminAdministrators:tab==='Audit Log'?adminAuditLogs:adminAffiliates;setItems(await fn())}catch(e){setError(e instanceof Error?e.message:'Unable to load admin data.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[tab]);
 const mutate=async(fn:()=>Promise<any>,msg:string)=>{if(pending)return;setPending(true);setNotice('');try{await fn();setNotice(msg);await load();if(selected)setSelected({...selected,account_status:selected.account_status==='ACTIVE'?'REVOKED':'ACTIVE'})}catch(e){setError(e instanceof Error?e.message:'Operation failed.')}finally{setPending(false)}};
 if(selected)return <main className="app-shell min-h-screen px-4 pt-safe"><button className="icon-button" onClick={()=>{setSelected(null);setDetail(null)}}>Back</button><h1 className="section-title mt-5">Affiliate Detail</h1><div className="glass-card mt-4 space-y-2 p-5"><h2 className="text-lg font-semibold">{selected.first_name||selected.username||`Affiliate #${selected.id}`}</h2><p>@{selected.username||'no username'}</p><p>Status: {selected.account_status||'ACTIVE'}</p><p>Telegram ID: {selected.telegram_id}</p><div className="mt-4 flex flex-wrap gap-2"><button className="icon-button" onClick={async()=>setDetail(await adminReferrals())}>View referrals</button><button className="icon-button" onClick={async()=>{try{setDetail(await adminPayout(selected.id))}catch(e){setError('No payout details found.')}}}>View payout</button>{selected.account_status==='REVOKED'?<button className="primary-button" disabled={pending} onClick={()=>mutate(()=>adminRestore(selected.id),'Affiliate restored')}>{pending?'Restoring...':'Restore'}</button>:<button className="primary-button" disabled={pending} onClick={()=>{if(confirm('Are you sure you want to revoke this affiliate? They will not be able to create another affiliate account or generate a new referral link until an administrator restores them.'))void mutate(()=>adminRevoke(selected.id),'Affiliate revoked')}}>{pending?'Revoking...':'Revoke'}</button>}</div>{detail&&<div className="mt-4 space-y-2">{detail.account_number?<><p>Account Name: {detail.account_name}</p><p>Bank Name: {detail.bank_name}</p><p>Account Number: {detail.account_number}</p></>:Array.isArray(detail)?detail.filter((r:any)=>r.referrer_id===selected.id).map((r:any)=><button className="glass-card block w-full p-3 text-left" key={r.id} onClick={async()=>setDetail(await adminReferral(r.id))}>Referral #{r.id}</button>):Object.entries(detail).map(([k,v])=><p key={k}><b>{k}</b>: {String(v)}</p>)}</div>}</div>{error&&<p role="alert" className="mt-3">{error}</p>}{notice&&<p className="mt-3 text-emerald-300">{notice}</p>}</main>;
 return <main className="app-shell min-h-screen px-4 pt-safe"><button className="icon-button" onClick={onBack}>Back</button><h1 className="section-title mt-5">Admin Dashboard</h1><nav className="mt-4 grid grid-cols-2 gap-2">{['Overview','Affiliates','Referrals','Administrators','Audit Log'].map(x=><button className="icon-button" key={x} onClick={()=>setTab(x)}>{x}</button>)}</nav>{loading?<div aria-label="Loading admin data" className="glass-card mt-5 h-48 animate-pulse"/>:error?<div><p role="alert">{error}</p><button className="primary-button" onClick={load}>Retry</button></div>:tab==='Overview'?<div className="mt-5 grid grid-cols-2 gap-3"><div className="glass-card p-4">Total affiliates: {items.length}</div><div className="glass-card p-4">Active affiliates: {items.filter(x=>x.account_status==='ACTIVE').length}</div><div className="glass-card p-4">Revoked affiliates: {items.filter(x=>x.account_status==='REVOKED').length}</div></div>:<section className="mt-5 space-y-3">{items.length===0?<p>No {tab.toLowerCase()} found.</p>:items.map(x=><button className="glass-card block w-full p-4 text-left" key={x.id} onClick={()=>tab==='Affiliates'&&setSelected(x)}><b>{x.username?`@${x.username}`:x.action||`#${x.id}`}</b><p className="text-sm text-zinc-400">{x.account_status||x.action||x.status||''}</p>{tab==='Administrators'&&!x.is_protected_admin&&<span className="text-xs">Manage</span>}</button>)}</section>}</main>;
}
