import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
const api = vi.hoisted(() => ({ getReferrals: vi.fn(), getReferral: vi.fn(), deleteAccount: vi.fn() }));
vi.mock('@/lib/api', () => api);
vi.mock('@/lib/telegram', () => ({ setTelegramBackButton: vi.fn(() => () => {}) }));
vi.mock('@/hooks/useDashboard', () => ({ useDashboard: () => ({ state: { status: 'ready', data: { profile: { user: { telegram_id: 1, first_name: 'Ada', photo_url: null }, referral_code: 'SMC-ABC' }, dashboard: { total_verified_referrals: 2, pending_referrals: 0, personal_referral_link: 'https://example.test/r', registration_form_url: null, recent_verified_activity: [] } } }, retry: vi.fn() }) }));
import App from '@/App';
const referrals = [{ id: 7, name: 'John Doe', course: 'Frontend Development', status: 'verified', created_at: '2026-01-01T00:00:00Z' }];
const dashboard = () => { localStorage.setItem('smc_referral_unlocked_1', '1'); return render(<App />); };
beforeEach(() => { localStorage.clear(); vi.clearAllMocks(); });

describe('dashboard', () => {
  it('renders the active dashboard controls', () => { render(<App />); expect(screen.getByText('View All Referrals')).toBeInTheDocument(); expect(screen.getByText('Delete Account')).toBeInTheDocument(); });
  it('orders link before code and opens My Referrals', async () => { api.getReferrals.mockResolvedValue({ referrals }); dashboard(); const link=screen.getByText('Personal link'), code=screen.getByText('Referral code'); expect(link.compareDocumentPosition(code)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy(); fireEvent.click(screen.getByText('View All Referrals')); await screen.findByText('John Doe'); expect(screen.getByText((_, element) => element?.textContent === 'Frontend Development · verified')).toBeInTheDocument(); });
});

describe('referral states', () => {
  it('shows list loading then success', async () => { let resolve!: (v:unknown)=>void; api.getReferrals.mockReturnValue(new Promise(r=>resolve=r)); dashboard(); fireEvent.click(screen.getByText('View All Referrals')); expect(screen.getByLabelText('Loading referrals')).toBeInTheDocument(); resolve({ referrals }); await screen.findByText('John Doe'); });
  it('shows list error and retries to empty state', async () => { api.getReferrals.mockRejectedValueOnce(new Error('fail')).mockResolvedValueOnce({referrals:[]}); dashboard(); fireEvent.click(screen.getByText('View All Referrals')); await screen.findByText('Unable to load your referrals.'); fireEvent.click(screen.getByText('Retry')); await screen.findByText('No Referrals Yet'); expect(screen.getByText(/start building your network/i)).toBeInTheDocument(); expect(api.getReferrals).toHaveBeenCalledTimes(2); });
  it('shows detail loading, labels, values, filtering, and back navigation', async () => { api.getReferrals.mockResolvedValue({referrals}); let resolve!: (v:unknown)=>void; api.getReferral.mockReturnValue(new Promise(r=>resolve=r)); dashboard(); fireEvent.click(screen.getByText('View All Referrals')); await screen.findByText('John Doe'); fireEvent.click(screen.getByText('John Doe')); expect(screen.getByLabelText('Loading referral details')).toBeInTheDocument(); resolve({fields:{Name:'John Doe','Phone Number':'08012345678',Email:'john@example.com',Course:'Frontend Development'}}); await screen.findByText('08012345678'); expect(screen.getByText('Phone Number')).toBeInTheDocument(); expect(screen.queryByText('response_id')).not.toBeInTheDocument(); fireEvent.click(screen.getByLabelText('Back')); expect(screen.getByText('My Referrals')).toBeInTheDocument(); fireEvent.click(screen.getByLabelText('Back')); expect(screen.getByText('View All Referrals')).toBeInTheDocument(); });
  it('shows detail error with usable Back', async () => { api.getReferrals.mockResolvedValue({referrals}); api.getReferral.mockRejectedValue(new Error('fail')); dashboard(); fireEvent.click(screen.getByText('View All Referrals')); await screen.findByText('John Doe'); fireEvent.click(screen.getByText('John Doe')); await screen.findByText('Unable to load referral details.'); fireEvent.click(screen.getByLabelText('Back')); expect(screen.getByText('My Referrals')).toBeInTheDocument(); });
});

describe('delete states', () => {
  it('cancel closes without deleting', () => { dashboard(); fireEvent.click(screen.getByText('Delete Account')); expect(screen.getByText('Delete Affiliate Account?')).toBeInTheDocument(); fireEvent.click(screen.getByText('Cancel')); expect(api.deleteAccount).not.toHaveBeenCalled(); });
  it('prevents duplicates and renders successful deletion', async () => { let resolve!:()=>void; api.deleteAccount.mockReturnValue(new Promise<void>(r=>resolve=r)); dashboard(); fireEvent.click(screen.getByText('Delete Account')); const confirm=screen.getAllByRole('button',{name:'Delete Account'}).at(-1)!; fireEvent.click(confirm); expect(screen.getByText('Deleting...')).toBeDisabled(); fireEvent.click(screen.getByText('Deleting...')); expect(api.deleteAccount).toHaveBeenCalledTimes(1); resolve(); await screen.findByText('Account Deleted'); expect(screen.queryByText('View All Referrals')).not.toBeInTheDocument(); });
  it('shows failure and permits retry', async () => { api.deleteAccount.mockRejectedValueOnce(new Error('Unable to delete')).mockResolvedValueOnce(undefined); dashboard(); fireEvent.click(screen.getByText('Delete Account')); fireEvent.click(screen.getAllByRole('button',{name:'Delete Account'}).at(-1)!); await screen.findByRole('alert'); fireEvent.click(screen.getAllByRole('button',{name:'Delete Account'}).at(-1)!); await screen.findByText('Account Deleted'); expect(api.deleteAccount).toHaveBeenCalledTimes(2); });
});
